name: Build Project

env:
  application_name: Showcaser

on:
  push:
    branches:
      - 'master'
  workflow_run:
    workflows: ["Test Project"]
    types:
      - success

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
            build-scan-publish: true
            build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
            build-scan-terms-of-use-agree: "yes"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK Release
      - name: Build Release Version (APK)
        run: ./gradlew assemble

      - name: Rename Release Version (APK)
        run: mv "./app/build/outputs/apk/release/app-release-unsigned.apk" "./app/build/outputs/apk/release/${{ env.application_name }}.apk"

      - name: Upload Release Version (APK)
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/release/${{ env.application_name }}.apk
